### ISSUE TITLE
Support building with Core CLR (on Linux)

### ISSUE THREAD

**Issue by dougbu** [aspnet/Universe#272]
Points to cover:
- [x] Use `IsLinux` and not `IsMono` when appropriate in `*.shade` files.
- [x] Remove `-runtime CLR -arch x86` from `dnvm use default` commands in `build.cmd` and `build.sh`. (Should run with whatever the user has chosen as `default`, even after aspnet/dnvm#405 is fixed.)
- [ ] Change `_k-test.shade` to skip tests for a different runtime than the current `default` on Linux. (Could also be more explicit on Windows and use `default -runtime CLR` as well as current `default -runtime CoreCLR`.)
- [x] Stretch: Extend `_k-test.shade` / `_k.shade` to support multiple runtimes on Linux. This requires either aspnet/dnvm#265 or aspnet/dnvm#405 to be fixed everywhere. Tests on Linux currently run using only the `default` runtime and the scripts assume that `default` is full CLR.
- [x] Optional: Work around aspnet/dnx#2566, allowing `build.sh` and `build.cmd` to build only for Core CLR. (`export "NUGET3_build_options= --quiet --framework dnxcore50"` and similar hacks mostly work.)

**Comment by BrennanConroy** [comment]
Bullet #2 dnvm issue has been fixed

**Comment by BrennanConroy** [comment]
aspnet/dnvm#265 and aspnet/dnvm#405 both fixed

**Comment by dougbu** [comment]
Thanks @BrennanConroy !  Have both fixes been pushed into Universe / KoreBuild?

**Comment by BrennanConroy** [comment]
Oh... I think we manually update that repo once in a while?

Sent from my HTC

----- Reply message -----

**Comment by muratg** [comment]
@dougbu is this still happening in beta 8? do we need to move it out?

**Comment by dougbu** [comment]
Yes, move it out. We've now got a `dnvm.sh` that supports this work but I haven't spent the necessary time in the `.shade` (files). My plan is to do the work early in RC1.

**Comment by dougbu** [comment]
2f76bcb
