### ISSUE TITLE
Add support for dotnet CLI

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#324]
### Blocking issues:

- [x] Restore fails for tools built with imports https://github.com/dotnet/cli/issues/1181
- [x] Update the lock file format https://github.com/aspnet/dnx/pull/3327
- [x] Downgrade to CLR RC2
- [x] Build fails for build time dependencies https://github.com/dotnet/cli/issues/1093 https://github.com/dotnet/cli/pull/1100
- [x] Publish skips native artifacts from project references https://github.com/dotnet/cli/issues/710
- [x] dotnet-restore Too many open files on Mac https://github.com/NuGet/Home/issues/2004 (Not blocking, but still present, we have a workaround)
- [x] Build places dependent project outputs wrong folder https://github.com/dotnet/cli/issues/987
- [x] No xunit xplat (using dnx on coreclr)
- [x] Null ref during tools restore https://github.com/dotnet/cli/issues/844
- [x] Microsoft.Extensions.DependencyModel package has the dotnet5.4 binary under net451 directory https://github.com/dotnet/cli/issues/882
- [x] `dotnet restore` leaves temporary folders behind (because the names are random and they cannot be gitignored) https://github.com/dotnet/cli/issues/811
- [x] Generate binding redirects for desktop CLR dlls https://github.com/dotnet/cli/issues/807
- [x] No xml doc generation https://github.com/dotnet/cli/issues/635
- [x] Cannot include extra file in the publish output folder
- [x] Can't reference System.Runtime design-time facade https://github.com/dotnet/cli/issues/691
- [x] No assembly file version attribute https://github.com/dotnet/cli/issues/714
- [x] https://github.com/dotnet/cli/issues/422
- [x] https://github.com/dotnet/cli/issues/408
- [x] Dependency on `dnu packages add`
- [x] xunit requires `dnx` on desktop CLR

### I want to upgrade my repo to dotnet. How do I do it?

See this as a reference: https://github.com/aspnet/Common/commit/2137b669f9323498547d6b0d415f4fbdaaeb0b00

### Work items:

- [x] Copy packages from external feeds https://github.com/aspnet/Universe/issues/362

### Done

- [x] MVC https://github.com/aspnet/Mvc/issues/3908
- [x] DnxWatch
- [x] Entropy https://github.com/aspnet/Entropy/issues/90
- [x] MusicStore https://github.com/aspnet/MusicStore/issues/586
- [x] Scaffolding https://github.com/aspnet/Scaffolding/issues/161
- [x] Performance https://github.com/aspnet/Performance/issues/17
- [x] ServerTests
- [x] IISIntegration
- [x] Localization https://github.com/aspnet/Localization/issues/198
- [x] WebSockets https://github.com/aspnet/WebSockets/issues/70
- [x] Microsoft.Data.Sqlite https://github.com/aspnet/Microsoft.Data.Sqlite/pull/212
- [x] Testing
- [x] BrowserLink https://github.com/aspnet/BrowserLink/issues/9
- [x] Razor Tooling https://github.com/aspnet/RazorTooling/issues/41
- [x] Benchmarks https://github.com/aspnet/benchmarks/issues/46
- [x] Glimpse* https://github.com/Glimpse/Glimpse.Prototype/issues/103
- [x] SignalR-ServiceBus  https://github.com/aspnet/SignalR-ServiceBus/issues/12
- [x] SignalR-Redis https://github.com/aspnet/SignalR-Redis/issues/23
- [x] SignalR-Server https://github.com/aspnet/SignalR-Server/issues/149
- [x] Security
- [x] AntiForgery
- [x] JsonPatch https://github.com/aspnet/JsonPatch/issues/9
- [x] Identity
- [x] libuv https://github.com/aspnet/libuv-build/issues/6
- [x] Routing https://github.com/aspnet/Routing/issues/277
- [x] StaticFiles
- [x] BasicMiddleware
- [x] WebListener
- [X] CORS
- [x] EF https://github.com/aspnet/EntityFramework/issues/4280
- [x] Razor https://github.com/aspnet/Razor/issues/657
- [x] Session
- [x] Diagnostics
- [x] Proxy
- [x] Common
- [x] FileProvider
- [x] Configuration
- [x] DependencyInjection
- [x] Logging
- [x] Options
- [x] DataProtection
- [x] HttpAbstractions
- [x] EventNotification
- [x] HtmlAbstractions
- [x] Caching
- [x] Hosting
- [x] Kestrel https://github.com/aspnet/KestrelHttpServer/issues/571
- [x] UserSecrets https://github.com/aspnet/UserSecrets/issues/56
- [x] SQL Cache tool https://github.com/aspnet/Caching/issues/144
- [x] SignalR-SqlServer https://github.com/aspnet/SignalR-SqlServer/issues/18

**Comment by muratg** [comment]
Yes, let's keep the current KoreBuild as is, since we will be porting the repos one by one, and in the meantime, we would need the existing KoreBuild to build repos that are not ported yet.

**Comment by bricelam** [comment]
Do we still intend to use Sake?

**Comment by victorhurdugaci** [comment]
AFAIK yes. Would you prefer something else?

**Comment by bricelam** [comment]
Oh I just noticed most of the other .NET Core repos were usin xplat MSBuild...

**Comment by muratg** [comment]
We can certainly discuss the options within the engineering team. Brice, feel free to start a discussion, and include Victor if you do :)

**Comment by davidfowl** [comment]
@bricelam nice one :smile:

**Comment by victorhurdugaci** [comment]
+1 for anything that's C# based
-1 for anything XML based

How about plain C# console apps? :)

**Comment by Eilon** [comment]
@victorhurdugaci that's under consideration as well.

**Comment by theonlylawislove** [comment]
What are the plans to support DNX web projects? As it stands now, when running KoreBuild with a web project, it just does a "dnu pack" on it. I'm wondering how we will "dnu publish" the web projects.

I just did [some quick testing](https://github.com/theonlylawislove/vNextAwesomeWeb/commit/0587006a566c05ac5e98101e8b4bce028b9ab74b), modifying the ```makefile.shade``` file to perform a "dnu publish", but there is no bower installed. Visual Studio works fine, it seems to be using some internal bower version. I imagine we will also have an issue with gulp/grunt not being recognized when executing the ```project.json```'s [scripts](https://github.com/theonlylawislove/vNextAwesomeWeb/blob/master/src/AwesomeWeb/project.json#L48).

Is this still a WIP? Is there another issue tracking this project type?

**Comment by victorhurdugaci** [comment]
KoreBuild is a what we use to build ASP.NET 5. It's not the recommended way to use Sake to build and publish web projects. Thus, it doesn't have support for many dnx features. There's no work item to add support for more than what we need to build ASP.NET. 

That being said, your change to the makefile looks okay. If you need bower, you have to install it as a separate step and then make it accessible to the build script by adding it to the PATH.

This particular work item is just to make the existing functionality work with dotnet CLI.

**Comment by theonlylawislove** [comment]
Hmm, that is interesting. I have been seeing KoreBuild used on other projects (even Web ones, like [here](https://github.com/aspnet/MusicStore/blob/dev/makefile.shade) and [here](https://github.com/OrchardCMS/Orchard2/blob/master/makefile.shade)) that have nothing to do with the web stack. I understand there is no documentation, but it seemed that this would be future of building .NET projects in general.

Looks like there is an opportunity here then for the community to create sets of commands that can be used in their build.

I'm curious why the [```#restore-bower-components```](https://github.com/aspnet/Universe/blob/5ed05d34acafb803164b46eeab8216a1f4752fe6/build/_k-standard-goals.shade#L48) was created then. Which library of the stack is using this?

**Comment by davidfowl** [comment]
There's 2 different components here:
- KoreBuild
- Sake

I expect that we'all move away from sake at some point when something better comes along. KoreBuild on he other hand will live on. It's an opinionated way to build projects. It relies on a certain directory structure but that's about it. If you can live with those opinions then it'll work great for your projects.

**Comment by davidfowl** [comment]
> I'm curious why the #restore-bower-components was created then. Which library of the stack is using this?

Either and mvc sample or music store

**Comment by natemcmaster** [comment]
One more datapoint to consider: we currently [depend on Mono to run Sake](https://github.com/aspnet/Universe/blob/5ed05d34acafb803164b46eeab8216a1f4752fe6/build.sh#L31) on osx/linux. We have several compatibility issues with Mono, Nuget, and Entity Framework. Can we use coreclr to run Sake instead?

**Comment by victorhurdugaci** [comment]
Sake doesn't run (yet?) on CoreCLR

**Comment by natemcmaster** [comment]
In that case, +1 for MSBuild, -1 for Sake.

**Comment by dougbu** [comment]
> Sake doesn't run (yet?) on CoreCLR

Last I looked, Sake ran fine on Core CLR. However aspnet/dnx#2566 (`dnu build` , `dnu pack` can't build for another framework when using Core) leads to a need to run many commands w/ Mono anyhow.

**Comment by victorhurdugaci** [comment]
How do you run it on CoreCLR? It seems to only have an exe in it

**Comment by natemcmaster** [comment]
> Sake ran fine on Core CLR

@dougbu could you mean *"Sake can launch CoreCLR"*? KoreBuild executes Sake using mono.

**Comment by dougbu** [comment]
@natemcmaster I meant it's possible to change KoreBuild to use Core CLR by default from `.shade` files. The "compatibility issues" you mentioned are primarily about what gets launched.

**Comment by victorhurdugaci** [comment]
But Sake itself doesn't run on CoreCLR, right?

**Comment by natemcmaster** [comment]
@victorhurdugaci correct, Sake.exe is executed against the full CLR (or mono), not CoreCLR.

**Comment by pranavkm** [comment]
cc @loudej

**Comment by theonlylawislove** [comment]
What benefit would you get making it a DNX project? It is a command line build tool. I can't imagine people will ever be using sake as a project.json command.

**Comment by victorhurdugaci** [comment]
@theonlylawislove the benefit of having it a DNX project is not needing mono at all. You can just have CoreCLR

**Comment by victorhurdugaci** [comment]
The work is happening [here](https://github.com/aspnet/Universe/tree/victorhu/dotnet) in case anyone needs the `KoreBuild-dotnet` package

**Comment by theonlylawislove** [comment]
Do the new commands require environment variables to be already established (via running dnvm use)? Or, does every command take a "use" command, and the application will internally load the appropriate dnx runtime?

**Comment by victorhurdugaci** [comment]
- `dotnet run -f <framework>` will run an application from sources on the specified framework. E.g: `dotnet run -f dnxcore50`
- If you run `dotnet compile`, you'll have executables for each framework

**Comment by victorhurdugaci** [comment]
https://github.com/aspnet/common now builds with dotnet

**Comment by victorhurdugaci** [comment]
If anyone wants to try to upgrade their repo to dotnet, use this as a reference: https://github.com/aspnet/Common/commit/2137b669f9323498547d6b0d415f4fbdaaeb0b00

**Comment by natemcmaster** [comment]
I tried to upgrade sqlite, but Mono 4.2.1 + nuget.exe do not agree. Are we making progress on removing our dependency on Mono to build and run?

**Comment by victorhurdugaci** [comment]
1. Use Mono 4.0.5, we know that 4.2.1 is buggy and you'll hit a lot of issues.
2. Delete the cached NuGet so it can pick the latest version: https://github.com/aspnet/Universe/blob/dev/build-template-dotnet/build.sh#L16-L27

**Comment by natemcmaster** [comment]
> Use Mono ... you'll hit a lot of issues.

A chronic problem. On EF [we just avoid mono altogether](https://github.com/aspnet/EntityFramework/blob/dev/tools/coreclr-build.sh) as Mono seems to be forever-broken. Can we create an x-plat build script that does not depend on Mono and use `dotnet` completely?

**Comment by davidfowl** [comment]
The only thing we'll use mono for is running tests. The cli and nuget will be xplat and self contained

**Comment by danroth27** [comment]
@piotrpMSFT

**Comment by muratg** [comment]
xunit runner issue (https://github.com/dotnet/cli/issues/18) seems to have something to test with now. @victorhurdugaci When can we test this?

**Comment by natemcmaster** [comment]
FWIW, dnx testing is no longer working for EF. DNX has not kept up with changes in corefx and on OSX El Capitan, parts of the BCL don't work on "dnxcore50" anymore. We can't test on x-plat until we get an xunit runner to replace dnx

**Comment by muratg** [comment]
I think someone said this morning that @anurse has a DNX change to remedy this?

**Comment by anurse** [comment]
https://github.com/aspnet/dnx/pull/3327 - I haven't had a chance to finish it and get it in. If someone wants to take it up, it should basically be working, just needs some quick testing and merging.

**Comment by davidfowl** [comment]
MVC is done!  /cc @pranavkm

**Comment by victorhurdugaci** [comment]
BAM! Closing this because it is done
